export default {
    INIT:'INIT',

    ENTITY_FETCHING_START: 'ENTITY_FETCHING_START',
    ENTITY_FETCHING_ERROR: 'ENTITY_FETCHING_ERROR',
    ENTITY_FETCHING_SUCCESS: 'ENTITY_FETCHING_SUCCESS',
    ENTITY_FETCHING_NO_RESULT: 'ENTITY_FETCHING_NO_RESULT',

    ENTITY_ADD_START: 'ENTITY_ADD_START',
    ENTITY_ADD_ERROR: 'ENTITY_ADD_ERROR',
    ENTITY_ADD_SUCCESS: 'ENTITY_ADD_SUCCESS',

    ENTITY_DELETE_START: 'ENTITY_DELETE_START',
    ENTITY_DELETE_ERROR: 'ENTITY_DELETE_ERROR',
    ENTITY_DELETE_SUCCESS: 'ENTITY_DELETE_SUCCESS',

    ENTITY_UPDATE_START: 'ENTITY_UPDATE_START',
    ENTITY_UPDATE_ERROR: 'ENTITY_UPDATE_ERROR',
    ENTITY_UPDATE_SUCCESS: 'ENTITY_UPDATE_SUCCESS',

	ENTITY_ADD_FORM_OPEN: 'ENTITY_ADD_FORM_OPEN',
	ENTITY_ADD_FORM_CHANGE: 'ENTITY_ADD_FORM_CHANGE',
	ENTITY_ADD_FORM_CLOSE: 'ENTITY_ADD_FORM_CLOSE',	
    
	ENTITY_UPDATE_FORM_OPEN: 'ENTITY_UPDATE_FORM_OPEN',
	ENTITY_UPDATE_FORM_CHANGE: 'ENTITY_UPDATE_FORM_CHANGE',
	ENTITY_UPDATE_FORM_CLOSE: 'ENTITY_UPDATE_FORM_CLOSE',	    

    NOTICE_ADD: 'NOTICE_ADD',
    NOTICE_CLEAR: 'NOTICE_CLEAR',
}